[package]
name = "smdiff-common"
version = "0.5.0"
edition = "2021"
repository = "https://github.com/ThinkingJoules/smdiff"
description = "Common structs, functions, and traits for smdiff format"
license = "MIT"

[dependencies]
