[package]
name = "smdiff-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smdiff-vcdiff ={ path = "../smdiff-vcdiff" }
smdiff-reader ={ path = "../smdiff-reader" }